#this file contains all kinematic properties for building the kinematic chain in diy_robotarm_macro.xacro
#these params are extracted from cad and represent DH-params

#NOTE: don't change properties in this file, because they are related to the reference sets, defined in cad construction for the links (in our case DH-convention was used)

#PI: 3.14159
#PI/2: 1.57079

kinematics:
  arm_shoulder:
    x: 0
    y: 0
    z: 0.10693
    roll: 0
    pitch: 0
    yaw: 0

  arm_upper_arm:
    x: 0.01163
    y: 0
    z: 0.05732
    roll: 1.57079
    pitch: 0
    yaw: 1.57079

  arm_forearm:
    x: 0
    y: 0.2032
    z: -0.04911
    roll: 0
    pitch: 0
    yaw: 1.57079

  arm_wrist_1:
    x: 0.1778
    y: 0
    z: 0.0103
    roll: 0
    pitch: 0
    yaw: 0

  arm_wrist_2:
    x: 0.03095
    y: 0
    z: 0.02667
    roll: -1.57079
    pitch: 0
    yaw: -1.57079

  arm_wrist_3:
    x: 0
    y: -0.04546
    z: 0.02683
    roll: 1.57079
    pitch: 0
    yaw: 0